# Generated by Django 6.0.2 on 2026-03-01 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='breakingnews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('inquiry', models.CharField(default='Inquiry type not specified', max_length=100)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Herosection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='Heropage')),
                ('cont', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='homepagearticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_catagory', models.CharField(default='Odisha', max_length=10)),
                ('image', models.ImageField(upload_to='articles/')),
                ('title', models.CharField(max_length=100)),
                ('odia_title', models.CharField(blank=True, max_length=100)),
                ('news_author', models.CharField(default='Bureau Report', max_length=20)),
                ('published_date', models.DateTimeField(default=datetime.datetime.now)),
                ('description', models.TextField(default='No description provided')),
                ('content', models.TextField(default='No news yet.')),
                ('video_link', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
