# Generated by Django 6.0.2 on 2026-03-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
