# Generated by Django 5.2.11 on 2026-03-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagearticle',
            name='reporter_area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='homepagearticle',
            name='reporter_image',
            field=models.ImageField(default='image not provided.', upload_to='reporterimage/'),
        ),
        migrations.AddField(
            model_name='homepagearticle',
            name='reporter_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='homepagearticle',
            name='reporter_phno',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='homepagearticle',
            name='reporter_position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
