# Generated by Django 6.0.2 on 2026-02-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_herosection_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='breakingnews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
        ),
    ]
