# Generated by Django 6.0.2 on 2026-03-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_herosection_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='cont',
        ),
    ]
