# Generated by Django 6.0.2 on 2026-03-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_delete_herosection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herosection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='Heropage')),
            ],
        ),
    ]
