# Generated by Django 6.0.2 on 2026-03-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_remove_herosection_cont'),
    ]

    operations = [
        migrations.CreateModel(
            name='authorpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('mail', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='authorpage/')),
            ],
        ),
    ]
