# Generated by Django 5.2.11 on 2026-02-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_breakingnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakingnews',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
