# Generated by Django 6.0.2 on 2026-02-22 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_breakingnews_id_alter_herosection_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='homepagearticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField(default=datetime.datetime.now)),
                ('description', models.TextField()),
            ],
        ),
    ]
