# Generated by Django 6.0.2 on 2026-02-22 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_homepagearticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagearticle',
            name='description',
        ),
    ]
