# Generated by Django 6.0.2 on 2026-02-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_remove_homepagearticle_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagearticle',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
    ]
