# Generated by Django 6.0.2 on 2026-02-23 14:33

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_homepagearticle_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='homepagevideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_catagory', models.CharField(max_length=10)),
                ('image', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('news_author', models.CharField(max_length=10)),
                ('published_date', models.DateTimeField(default=datetime.datetime.now)),
                ('description', models.TextField(default='No description provided')),
            ],
        ),
        migrations.AddField(
            model_name='homepagearticle',
            name='news_author',
            field=models.CharField(default=datetime.datetime(2026, 2, 23, 14, 32, 41, 19296, tzinfo=datetime.timezone.utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepagearticle',
            name='news_catagory',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
