# Generated by Django 6.0.2 on 2026-02-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_homepagevideo_homepagearticle_news_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagevideo',
            name='news_catagory',
            field=models.CharField(default='World', max_length=10),
        ),
    ]
