# Generated by Django 6.0.2 on 2026-02-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_alter_homepagevideo_news_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagevideo',
            name='news_author',
            field=models.CharField(default='Bureau Report', max_length=10),
        ),
    ]
