# Generated by Django 6.0.2 on 2026-02-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_alter_homepagevideo_news_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagevideo',
            name='news_catagory',
            field=models.CharField(default='Odisha', max_length=10),
        ),
    ]
