# Generated by Django 6.0.2 on 2026-02-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_alter_homepagevideo_news_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagearticle',
            name='news_author',
            field=models.CharField(default='Bureau Report', max_length=10),
        ),
        migrations.AlterField(
            model_name='homepagearticle',
            name='news_catagory',
            field=models.CharField(default='Odisha', max_length=10),
        ),
    ]
