# Generated by Django 6.0.2 on 2026-02-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_alter_homepagearticle_news_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagearticle',
            name='news_author',
            field=models.CharField(default='Bureau Report', max_length=20),
        ),
        migrations.AlterField(
            model_name='homepagevideo',
            name='news_author',
            field=models.CharField(default='Bureau Report', max_length=20),
        ),
    ]
