# Generated by Django 6.0.2 on 2026-02-26 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_alter_breakingnews_id_alter_herosection_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='homepagevideo',
        ),
    ]
