# Generated by Django 6.0.2 on 2026-02-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_delete_homepagevideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagearticle',
            name='image',
            field=models.ImageField(upload_to='articles/'),
        ),
    ]
