# Generated by Django 6.0.2 on 2026-02-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_alter_homepagearticle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='image',
            field=models.ImageField(upload_to='Heropage'),
        ),
    ]
