# Generated by Django 6.0.2 on 2026-02-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0021_alter_breakingnews_id_alter_herosection_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagearticle',
            name='news',
            field=models.TextField(default='No News Yet.'),
        ),
        migrations.AddField(
            model_name='homepagearticle',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
