# Generated by Django 6.0.2 on 2026-02-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0022_homepagearticle_news_homepagearticle_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagearticle',
            old_name='news',
            new_name='content',
        ),
    ]
