# Generated by Django 6.0.2 on 2026-02-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0023_rename_news_homepagearticle_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagearticle',
            name='content',
        ),
        migrations.RemoveField(
            model_name='homepagearticle',
            name='slug',
        ),
    ]
