# Generated by Django 6.0.2 on 2026-02-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0024_remove_homepagearticle_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagearticle',
            name='content',
            field=models.TextField(default='No news yet.'),
        ),
        migrations.AddField(
            model_name='homepagearticle',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
