# Generated by Django 6.0.2 on 2026-02-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0025_homepagearticle_content_homepagearticle_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagearticle',
            name='odia_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
